import { JobsContextProvider } from "@/context";
import "./global.css";

export const metadata = {
  title: "Github Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center ">
        <JobsContextProvider>{children}</JobsContextProvider>
      </body>
    </html>
  );
}
